### PR TITLE
creating a server

### PR DESCRIPTION
**Pull request by Alice-babayalo**

### CODE REVIEW

**Review by hirwajeaneric — CHANGES_REQUESTED** [review]
Please add real server codes.
istock-1173805290-1

**Review by beylar — CHANGES_REQUESTED** [review]
Please create server

**Review by mireilleIrafasha25 — DISMISSED** [review]

**Review by Depha56 — COMMENTED** [review]
bad codes

**Review by kezagiselle — COMMENTED** [review]
no comment

**Review by charite-uwatwembi — COMMENTED** [review]
modify your codes

**Comment by Joh-Ishimwe** [comment]
Hhhhh

**Review by CYNTHIA-IGIHOZO — CHANGES_REQUESTED** [review]
change this

**Review by CYNTHIA-IGIHOZO — COMMENTED** [review]
good

**Pull request closed without merging**
