### PR TITLE
renamed index.js to app.js and modified other files

### PR DESCRIPTION
**Pull request by Aline-CROIRE**

### CODE REVIEW

**Review by Yvonneizerimana — COMMENTED** [review]
Nice Job

**Review by Yvonneizerimana — APPROVED** [review]

**Review by Ange290 — APPROVED** [review]

**Review by mbienaimee — APPROVED** [review]

**Review by kezagiselle — APPROVED** [review]

**Review by Alice-babayalo — COMMENTED** [review]
good

**Review by Bakazikevine — APPROVED** [review]

**Review by Alice-babayalo — APPROVED** [review]
nice

**Review by anithasandrine — APPROVED** [review]
well done

**Review by uwinezagloria — APPROVED** [review]

**Pull request merged**
